

export enum TransformFlag {
  ECU = 'ecuador.png',
  NED = 'netherlands.png',
  QAT = 'qatar.png',
  SEN = 'senegal.png',
  ENG = 'england.png',
  IRN = 'iran.png',
  USA = 'usa.png',
  WAL = 'wales.png',
  ARG = 'argentina.png',
  MEX = 'mexico.png',
  POL = 'poland.png',
  KSA = 'saudiArabia.png',
  AUS = 'australia.png',
  DEN = 'denmark.png',
  FRA = 'france.png',
  TUN = 'tunisia.png',
  CRC = 'costaRica.png',
  GER = 'germany.png',
  JPN = 'japan.png',
  ESP = 'spain.png',
  BEL = 'belgium.png',
  CAN = 'canada.png',
  CRO = 'croatia.png',
  MAR = 'morocco.png',
  BRA = 'brazil.png',
  CMR = 'cameroon.png',
  SRB = 'serbia.png',
  SUI = 'swiss.png',
  GHA = 'ghana.png',
  KOR = 'sKorea.png',
  POR = 'portugal.png',
  URU = 'uruguay.png'
}
